# Generated by Django 5.2.8 on 2025-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('assignedRecruiter', models.CharField(max_length=255)),
                ('jdFile', models.FileField(blank=True, null=True, upload_to='job_files/')),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
