# Generated by Django 5.2.8 on 2025-11-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='assignedRecruiter',
            new_name='assigned_recruiter',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='posted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jdFile',
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
