# Generated by Django 5.2.8 on 2025-11-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_skills_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills_required',
            new_name='required_skills',
        ),
    ]
