# Generated by Django 5.2.8 on 2025-11-16 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_accountsuser_delete_customuser'),
        ('jobs', '0007_rename_skills_required_job_required_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_chat_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages', to='accounts.accountsuser')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='jobs.jobapplication')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='accounts.accountsuser')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['application', 'created_at'], name='chat_chatme_applica_1718f9_idx'), models.Index(fields=['ai_chat_user', 'created_at'], name='chat_chatme_ai_chat_8e01c9_idx')],
            },
        ),
    ]
