# Generated by Django 5.2.8 on 2025-11-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountsuser_delete_customuser'),
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='user_name',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='accounts.accountsuser'),
            preserve_default=False,
        ),
    ]
